# docker-compose.yaml

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - chat-network

  frontend:
    build:
      context: ./frontend_chat
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "80:3000" 
    depends_on:
      - backend
    networks:
      - chat-network

networks:
  chat-network:
    external: true
