services:
  db:
    image: pgvector/pgvector:0.7.4-pg17
    container_name: postgres_vector
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - chat-network

networks:
  chat-network:
    external: true

volumes:
  pgdata:
